# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20170518_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.BigIntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.BigIntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
