# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20170518_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
