# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20170518_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
    ]
