# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_venta_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_cliente',
        ),
    ]
