# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_auto_20170518_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
